const recipeData = [
  {
    "id": 1,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Pizza-Noodle-Bake_EXPS_GHBZ18_40275_C08_30_3b-8.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/pizza-noodle-bake/",
    "recipeTitle": "Pizza Noodle Bake",
    "cookingTimeDetails": "Prep: 25 min. Bake: 15 min.",
    "servings": "6 servings",
    "ingredients": ["10 ounces uncooked egg noodles", "1-1/2 pounds ground beef", "1/2 cup finely chopped onion", "1/4 cup chopped green pepper", "1 jar (14 ounces) pizza sauce", "1 can (4 ounces) mushroom stems and pieces, drained", "1 cup shredded cheddar cheese", "1 cup shredded part-skim mozzarella cheese", "1 package (3-1/2 ounces) sliced pepperoni"],
    "directions": ["Cook noodles according to package directions. Meanwhile, in a large skillet, cook the beef, onion and green pepper over medium heat until meat is no longer pink, breaking the meat into crumbles; drain. Add pizza sauce and mushrooms; heat through.", "Drain noodles. In a greased 13x9-in. baking dish, layer half the noodles, half the beef mixture, 1/2 cup of each cheese and half the pepperoni. Repeat layers. Cover and bake at 350° for 15-20 minutes or until heated through.", "Freeze option: Cover and freeze unbaked casserole for up to 3 months. Remove from freezer 30 minutes before baking (do not thaw). Cover and bake at 350° for 45-50 minutes. Uncover; bake 15-20 minutes longer or until heated through."],
    "nutritionDetails": "1-1/3 cups: 644 calories, 33g fat (15g saturated fat), 160mg cholesterol, 913mg sodium, 42g carbohydrate (6g sugars, 4g fiber), 43g protein."
  },
  {
    "id": 2,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Enchilada-Casser-Ole-_EXPS_WRSM17_42083_C03_22_2b-5.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/enchilada-casser-ole/",
    "recipeTitle": "Enchilada Casser-Ole!",
    "cookingTimeDetails": "Prep: 25 min. Bake: 30 min.",
    "servings": "8 servings",
    "ingredients": ["1 pound lean ground beef (90% lean)", "1 large onion, chopped", "2 cups salsa", "1 can (15 ounces) black beans, rinsed and drained", "1/4 cup reduced-fat Italian salad dressing", "2 tablespoons reduced-sodium taco seasoning", "1/4 teaspoon ground cumin", "6 flour tortillas (8 inches)", "3/4 cup reduced-fat sour cream", "1 cup shredded reduced-fat Mexican cheese blend", "1 cup shredded lettuce", "1 medium tomato, chopped", "1/4 cup minced fresh cilantro"],
    "directions": ["In a large skillet, cook beef and onion over medium heat until meat is no longer pink; drain. Stir in the salsa, beans, dressing, taco seasoning and cumin. Place 3 tortillas in an 11x7-in. baking dish coated with cooking spray. Layer with half of the meat mixture, sour cream and cheese. Repeat layers.", "Cover and bake at 400° for 25 minutes. Uncover; bake until heated through, 5-10 minutes longer. Let stand for 5 minutes; top with lettuce, tomato and cilantro."],
    "nutritionDetails": "1 piece: 357 calories, 12g fat (5g saturated fat), 45mg cholesterol, 864mg sodium, 37g carbohydrate (6g sugars, 3g fiber), 23g protein. Diabetic Exchanges: 3 lean meat, 2 starch, 1 vegetable, 1 fat."
  },
  {
    "id": 3,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Cheeseburger-Cups_EXPS_GBBZ19_45599_E11_13_11b-9.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/cheeseburger-cups/",
    "recipeTitle": "Cheeseburger Cups",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "5 servings",
    "ingredients": ["1 pound ground beef", "1/2 cup ketchup", "2 tablespoons brown sugar", "1 tablespoon prepared mustard", "1-1/2 teaspoons Worcestershire sauce", "1 tube (12 ounces) refrigerated buttermilk biscuits", "1/2 cup cubed Velveeta"],
    "directions": ["In a large skillet, cook beef over medium heat until no longer pink, breaking it into crumbles; drain. Stir in the ketchup, brown sugar, mustard and Worcestershire sauce. Remove from the heat; set aside.", "Press each biscuit onto the bottom and up the sides of a greased muffin cup. Spoon beef mixture into cups; top with cheese cubes. Bake at 400° for 14-16 minutes or until cups are golden brown.", "Freeze option: Freeze cooled pastries in a freezer container, separating layers with waxed paper. To use, thaw pastries in the refrigerator for 8 hours. Reheat on a baking sheet in a preheated 375° oven until heated through."],
    "nutritionDetails": "2 cheeseburger cups: 440 calories, 16g fat (7g saturated fat), 78mg cholesterol, 1142mg sodium, 45g carbohydrate (13g sugars, 0 fiber), 27g protein."
  },
  {
    "id": 4,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Makeover-Li-l-Cheddar-Meat-Loaves_EXPS_DSBZ17_40731_C01_19_3b-9.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/makeover-li-l-cheddar-meat-loaves/",
    "recipeTitle": "Makeover Li’l Cheddar Meat Loaves",
    "cookingTimeDetails": "Prep: 15 min. Bake: 25 min.",
    "servings": "8 servings",
    "ingredients": ["2 large egg whites, beaten", "3/4 cup fat-free milk", "1 cup shredded reduced-fat cheddar cheese", "3/4 cup quick-cooking oats", "1 medium onion, chopped", "1 medium carrot, shredded", "1/2 teaspoon salt", "3/4 pound lean ground beef (90% lean)", "2/3 cup ketchup", "2 tablespoons brown sugar", "1-1/2 teaspoons prepared mustard"],
    "directions": ["In a large bowl, whisk egg whites and milk. Stir in the cheese, oats, onion, carrot and salt. Crumble beef over mixture and mix well.", "Shape into eight loaves; place in a 13x9-in. baking dish coated with cooking spray. In a small bowl, combine the ketchup, brown sugar and mustard; spoon over loaves.", "Bake, uncovered, at 350° for 25-30 minutes or until no pink remains and a thermometer reads 160°."],
    "nutritionDetails": "1 meat loaf: 187 calories, 7g fat (3g saturated fat), 36mg cholesterol, 550mg sodium, 18g carbohydrate (11g sugars, 1g fiber), 15g protein. Diabetic Exchanges: 2 lean meat, 1 starch."
  },
  {
    "id": 5,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps17270_CW153049D04_01_3b-5.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/slow-cooker-mac-and-cheese/",
    "recipeTitle": "Slow-Cooker Mac and Cheese",
    "cookingTimeDetails": "Prep: 15 min. Cook: 3-3/4 hours",
    "servings": "10 servings",
    "ingredients": ["1 package (16 ounces) elbow macaroni", "1/2 cup butter, melted", "4 cups shredded cheddar cheese, divided", "1 can (12 ounces) evaporated milk", "1 can (10-3/4 ounces) condensed cheddar cheese soup, undiluted", "1 cup 2% milk", "2 large eggs, beaten", "1/8 teaspoon paprika"],
    "directions": ["Cook macaroni according to package directions; drain. Place in a 5-qt. slow cooker; add butter. In a large bowl, mix 3 cups cheese, evaporated milk, condensed soup, 2% milk and eggs. Pour over macaroni mixture; stir to combine. Cook, covered, on low for 3-1/2 to 4 hours or until a thermometer reads at least 160°.", "Sprinkle with remaining cheese. Cook, covered, on low until cheese is melted, 15-20 minutes longer. Sprinkle with paprika."],
    "nutritionDetails": "1 serving: 502 calories, 28g fat (18g saturated fat), 131mg cholesterol, 638mg sodium, 42g carbohydrate (7g sugars, 2g fiber), 21g protein."
  },
  {
    "id": 6,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Chicken-Nuggets_EXPS_SDON18_1500_E06_13_1b-13.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/chicken-nuggets/",
    "recipeTitle": "Chicken Nuggets",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "8 servings",
    "ingredients": ["1 cup all-purpose flour", "4 teaspoons seasoned salt", "1 teaspoon poultry seasoning", "1 teaspoon ground mustard", "1 teaspoon paprika", "1/2 teaspoon pepper", "2 pounds boneless skinless chicken breasts", "1/4 cup canola oil"],
    "directions": ["In a large shallow dish, combine the first 6 ingredients. Flatten chicken to 1/2-in. thickness, then cut into 1-1/2-in. pieces. Add chicken, a few pieces at a time, to dish and turn to coat.", "In a large skillet, cook chicken in oil in batches until meat is no longer pink, 6-8 minutes."],
    "nutritionDetails": "3 ounces cooked chicken: 212 calories, 10g fat (2g saturated fat), 63mg cholesterol, 435mg sodium, 6g carbohydrate (0 sugars, 0 fiber), 24g protein. Diabetic Exchanges: 3 lean meat, 1-1/2 fat, 1/2 starch."
  },
  {
    "id": 7,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Walking-Tacos_exps101359_TH143192C02_11_3bC_RMS-4.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/walking-tacos/",
    "recipeTitle": "Walking Tacos",
    "cookingTimeDetails": "Prep: 10 min. Cook: 30 min.",
    "servings": "5 servings",
    "ingredients": ["1 pound ground beef", "1 envelope reduced-sodium chili seasoning mix", "1/4 teaspoon pepper", "1 can (10 ounces) diced tomatoes and green chiles", "1 can (15 ounces) Ranch Style beans (pinto beans in seasoned tomato sauce)", "5 packages (1 ounce each) corn chips", "Toppings: Shredded cheddar cheese, sour cream and sliced green onions"],
    "directions": ["In a large skillet, cook beef over medium heat until no longer pink, breaking into crumbles, 6-8 minutes; drain. Stir in chili seasoning mix, pepper, tomatoes and beans; bring to a boil. Reduce heat; simmer, uncovered, until thickened, 20-25 minutes, stirring occasionally.", "Just before serving, cut open corn chip bags. Add beef mixture and toppings."],
    "nutritionDetails": "1 serving (calculated without toppings): 530 calories, 28g fat (6g saturated fat), 56mg cholesterol, 1017mg sodium, 44g carbohydrate (5g sugars, 6g fiber), 24g protein."
  },
  {
    "id": 8,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps43840_SD153319C10_14_5b_WEB-4.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/homemade-fish-sticks/",
    "recipeTitle": "Homemade Fish Sticks",
    "cookingTimeDetails": "Prep/Total Time: 25 min.",
    "servings": "2 servings",
    "ingredients": ["1/2 cup dry bread crumbs", "1/2 teaspoon salt", "1/2 teaspoon paprika", "1/2 teaspoon lemon-pepper seasoning", "1/2 cup all-purpose flour", "1 large egg, beaten", "3/4 pound cod fillets, cut into 1-inch strips", "Butter-flavored cooking spray"],
    "directions": ["Preheat oven to 400°. In a shallow bowl, mix bread crumbs and seasonings. Place flour and egg in separate shallow bowls. Dip fish in flour to coat both sides; shake off excess. Dip in egg, then in crumb mixture, patting to help coating adhere.", "Place on a baking sheet coated with cooking spray; spritz with butter-flavored cooking spray. Bake 10-12 minutes or until fish just begins to flake easily with a fork, turning once."],
    "nutritionDetails": "1 serving: 278 calories, 4g fat (1g saturated fat), 129mg cholesterol, 718mg sodium, 25g carbohydrate (2g sugars, 1g fiber), 33g protein. Diabetic Exchanges: 4 lean meat, 1-1/2 starch."
  },
  {
    "id": 9,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps18427______FM143298B03_11_5b-6.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/mozzarella-baked-spaghetti/",
    "recipeTitle": "Mozzarella Baked Spaghetti",
    "cookingTimeDetails": "Prep: 20 min. Bake: 30 min. + standing",
    "servings": "8 servings",
    "ingredients": ["8 ounces uncooked spaghetti, broken into thirds", "1 large egg", "1/2 cup whole milk", "1/2 teaspoon salt", "1/2 pound ground beef", "1/2 pound bulk Italian sausage", "1 small onion, chopped", "1/4 cup chopped green pepper", "1 jar (14 ounces) meatless spaghetti sauce", "1 can (8 ounces) tomato sauce", "1 to 2 cups shredded part-skim mozzarella cheese"],
    "directions": ["Preheat oven to 350°. Cook spaghetti according to package directions.", "Meanwhile, in a large bowl, beat egg, milk and salt. Drain spaghetti; add to egg mixture and toss to coat. Transfer to a greased 13x9-in. baking dish.", "In a large skillet, cook beef, sausage, onion and green pepper over medium heat until meat is no longer pink; drain. Stir in spaghetti sauce and tomato sauce. Spoon over the spaghetti mixture.", "Bake, uncovered, 20 minutes. Sprinkle with the cheese. Bake 10 minutes longer or until cheese is melted. Let stand 10 minutes before cutting.", "Freeze option: Cool spaghetti completely before tossing with egg mixture. Transfer to baking dish; cover and refrigerate. Meanwhile, prepare meat sauce and cool completely before spooning over spaghetti mixture. Cover and freeze unbaked casserole. To use, partially thaw in refrigerator overnight. Remove from refrigerator 30 minutes before baking. Preheat oven to 350°. Bake as directed, increasing time as necessary to heat through and for a thermometer inserted in center to read 165°."],
    "nutritionDetails": "1 serving: 286 calories, 11g fat (5g saturated fat), 65mg cholesterol, 718mg sodium, 29g carbohydrate (6g sugars, 2g fiber), 17g protein."
  },
  {
    "id": 10,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Pizza-Meat-Loaf-Cups_EXPS_SDFM18_19241_D10_11_4b-1.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/pizza-meat-loaf-cups/",
    "recipeTitle": "Pizza Meat Loaf Cups",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "1 dozen",
    "ingredients": ["1 large egg, lightly beaten", "1/2 cup pizza sauce", "1/4 cup seasoned bread crumbs", "1/2 teaspoon Italian seasoning", "1-1/2 pounds ground beef", "1-1/2 cups shredded part-skim mozzarella cheese", "Optional: Additional pizza sauce and basil leaves"],
    "directions": ["Preheat oven to 375°. In a large bowl, mix first 4 ingredients. Add beef; mix lightly but thoroughly. Divide into 12 portions; press each onto the bottom and up sides of a greased muffin cup. Add cheese to centers.", "Bake until meat is cooked through, 15-18 minutes. If desired, top with additional sauce and basil before serving.", "Freeze option: Freeze cooled meat loaves in freezer containers. To use, partially thaw in refrigerator overnight. Microwave, covered, on high in a microwave-safe dish until heated through."],
    "nutritionDetails": "2 meat loaf cups: 327 calories, 20g fat (8g saturated fat), 119mg cholesterol, 416mg sodium, 6g carbohydrate (2g sugars, 1g fiber), 29g protein."
  },
  {
    "id": 11,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps11451_TH163622D04_12_7b.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/confetti-spaghetti/",
    "recipeTitle": "Confetti Spaghetti",
    "cookingTimeDetails": "Prep: 20 min. Bake: 35 min.",
    "servings": "12 servings",
    "ingredients": ["1 package (16 ounces) spaghetti", "1-1/2 pounds ground beef", "1 medium green pepper, chopped", "1 medium onion, chopped", "1 can (14-1/2 ounces) diced tomatoes, undrained", "1 can (8 ounces) tomato sauce", "1 tablespoon brown sugar", "1 teaspoon salt", "1 teaspoon chili powder", "1/2 teaspoon pepper", "1/4 teaspoon garlic powder", "1/8 teaspoon cayenne pepper", "3/4 cup shredded cheddar cheese"],
    "directions": ["Preheat oven to 350°. Cook spaghetti according to package directions. Meanwhile, in a large skillet, cook beef, green pepper and onion over medium heat until meat is no longer pink; drain. Stir in next 8 ingredients. Drain spaghetti; add to beef mixture.", "Transfer to a greased 13x9-in. baking dish. Cover and bake 30 minutes. Uncover; sprinkle with cheese. Bake until cheese is melted, about 5 minutes longer.", "Freeze option: Freeze cooled spaghetti mixture in freezer containers. To use, partially thaw in refrigerator overnight. Heat through in a covered saucepan over low heat, stirring gently; add water if necessary."],
    "nutritionDetails": "1 cup: 259 calories, 10g fat (4g saturated fat), 42mg cholesterol, 424mg sodium, 27g carbohydrate (4g sugars, 2g fiber), 16g protein."
  },
  {
    "id": 12,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Easy-Stuffed-Shells_exps42632_TH143193B04_23_6b_RMS-6.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/easy-stuffed-shells/",
    "recipeTitle": "Easy Stuffed Shells",
    "cookingTimeDetails": "Prep: 20 min. Bake: 40 min.",
    "servings": "12 servings",
    "ingredients": ["36 uncooked jumbo pasta shells", "1 jar (24 ounces) spaghetti sauce", "36 frozen fully cooked Italian meatballs (1/2 ounce each), thawed", "2 cups shredded part-skim mozzarella cheese"],
    "directions": ["Preheat oven to 350°. Cook pasta shells according to package directions; drain and rinse in cold water.", "Spread 1/2 cup sauce into a greased 13x9-in. baking dish. Fill each shell with a meatball; place over sauce. Top with remaining sauce and the cheese.", "Bake, covered, 35 minutes. Uncover; bake until bubbly and cheese is melted, 3-5 minutes longer."],
    "nutritionDetails": "3 stuffed shells: 334 calories, 17g fat (8g saturated fat), 45mg cholesterol, 711mg sodium, 30g carbohydrate (6g sugars, 3g fiber), 16g protein."
  },
  {
    "id": 13,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps38634_SD153323D06_05_2b-15.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/mexi-mac-skillet/",
    "recipeTitle": "Mexi-Mac Skillet",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "4 servings",
    "ingredients": ["1 pound extra-lean ground beef (95% lean)", "1 large onion, chopped", "1-1/4 teaspoons chili powder", "1 teaspoon dried oregano", "1/4 teaspoon salt", "1 can (14-1/2 ounces) diced tomatoes, undrained", "1 can (8 ounces) tomato sauce", "1 cup fresh or frozen corn", "1/2 cup water", "2/3 cup uncooked elbow macaroni", "1/2 cup shredded reduced-fat cheddar cheese"],
    "directions": ["In a large nonstick skillet, cook beef with onion over medium-high heat until no longer pink, 5-7 minutes; crumble meat.", "Stir in seasonings, tomatoes, tomato sauce, corn and water; bring to a boil. Stir in macaroni. Reduce heat; simmer, covered, until macaroni is tender, 15-20 minutes, stirring occasionally. Sprinkle with cheese."],
    "nutritionDetails": "1-1/4 cups: 318 calories, 10g fat (4g saturated fat), 75mg cholesterol, 755mg sodium, 28g carbohydrate (9g sugars, 5g fiber), 32g protein. Diabetic Exchanges: 1 starch, 3 lean meat, 1 vegetable."
  },
  {
    "id": 14,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Tater-Tot-chos_exps175046_TH14191C11_21_2b_RMS-5.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/tater-tot-chos/",
    "recipeTitle": "Tater Tot-chos",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "6 servings",
    "ingredients": ["4 cups frozen miniature Tater Tots", "1 pound ground beef", "1 envelope reduced-sodium taco seasoning", "2/3 cup water", "1/2 cup shredded cheddar cheese", "2 cups shredded lettuce", "1/4 cup sliced ripe olives, optional", "1/4 cup taco sauce", "1/2 cup sour cream"],
    "directions": ["Bake Tater Tots according to package directions.", "Meanwhile, in a large skillet, cook beef over medium heat until no longer pink, breaking into crumbles, 6-8 minutes; drain. Stir in taco seasoning and water. Bring to a boil; cook and stir until thickened, about 2 minutes.", "To serve, top Tater Tots with beef mixture, cheese, lettuce and, if desired, olives. Serve with taco sauce and sour cream."],
    "nutritionDetails": "1 serving: 375 calories, 23g fat (9g saturated fat), 70mg cholesterol, 828mg sodium, 27g carbohydrate (4g sugars, 2g fiber), 18g protein."
  },
  {
    "id": 15, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Slow-Cooker-Pizza-Casserole_exps33532_SSC2919296A03_21_2bC_RMS.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/slow-cooker-pizza-casserole/",
    "recipeTitle": "Slow-Cooker Pizza Casserole",
    "cookingTimeDetails": "Prep: 20 min. Cook: 2 hours",
    "servings": "14 servings",
    "ingredients": ["1 package (16 ounces) rigatoni or large tube pasta", "1-1/2 pounds ground beef", "1 small onion, chopped", "4 cups shredded part-skim mozzarella cheese", "2 cans (15 ounces each) pizza sauce", "1 can (10-3/4 ounces) condensed cream of mushroom soup, undiluted", "1 package (8 ounces) sliced pepperoni", "Chopped fresh basil or arugula, optional"],
    "directions": ["Cook pasta according to package directions. Meanwhile, in a skillet, cook beef and onion over medium heat until meat is no longer pink; drain.", "Drain pasta; place in a 5-qt. slow cooker. Stir in the beef mixture, cheese, pizza sauce, soup and pepperoni. Cover and cook on low for 2-3 hours or until heated through. If desired, top with basil before serving."],
    "nutritionDetails": "1 cup: 329 calories, 19g fat (8g saturated fat), 57mg cholesterol, 885mg sodium, 16g carbohydrate (5g sugars, 2g fiber), 22g protein."
  },
  {
    "id": 16, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps15037_SDAM17_15037_B12_09_3b_RMS.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/spanish-noodles-ground-beef/",
    "recipeTitle": "Spanish Noodles & Ground Beef",
    "cookingTimeDetails": "Prep/Total Time: 25 min.",
    "servings": "4 servings",
    "ingredients": ["1 pound ground beef", "1 small green pepper, chopped", "1/3 cup chopped onion", "3-1/4 cups uncooked medium egg noodles (about 6 ounces)", "1 can (14-1/2 ounces) diced tomatoes, undrained", "1-1/2 cups water", "1/4 cup chili sauce", "1/4 teaspoon salt", "1/8 teaspoon pepper", "4 bacon strips, cooked and crumbled"],
    "directions": ["In a large skillet, cook beef with green pepper and onion over medium heat until no longer pink, 5-7 minutes; crumble beef; drain.", "Stir in noodles, tomatoes, water, chili sauce, salt and pepper; bring to a boil. Reduce heat; simmer, covered, until noodles are tender, 15-20 minutes, stirring frequently. Top with bacon."],
    "nutritionDetails": "1-1/2 cups: 409 calories, 18g fat (6g saturated fat), 104mg cholesterol, 756mg sodium, 33g carbohydrate (8g sugars, 3g fiber), 28g protein."
  },
  {
    "id": 17,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps17782_FF163882B01_14_2b.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/sloppy-joe-pasta/",
    "recipeTitle": "Sloppy Joe Pasta",
    "cookingTimeDetails": "Prep: 20 min. Bake: 30 min.",
    "servings": "6 servings",
    "ingredients": ["1 pound ground beef", "1 envelope sloppy joe mix", "1 cup water", "1 can (8 ounces) tomato sauce", "1 can (6 ounces) tomato paste", "1 package (7 ounces) small shell pasta, cooked and drained", "1 cup 4% cottage cheese", "1/2 cup shredded cheddar cheese"],
    "directions": ["In a Dutch oven, cook beef over medium heat until no longer pink, breaking it into crumbles; drain. Stir in the sloppy joe mix, water, tomato sauce and tomato paste; heat through. Remove from the heat; stir in pasta.", "Spoon half the mixture into a greased 2-1/2-qt. baking dish. Top with cottage cheese and remaining pasta mixture. Sprinkle with cheddar cheese.", "Bake, uncovered, at 350° for 30-35 minutes or until bubbly and cheese is melted."],
    "nutritionDetails": "1-1/4 cups: 291 calories, 11g fat (6g saturated fat), 55mg cholesterol, 904mg sodium, 24g carbohydrate (7g sugars, 2g fiber), 23g protein."
  },
  {
    "id": 18, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Cheeseburger-Pockets_exps13674_FF2282132D03_02_5bC_RMS-2.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/cheeseburger-pockets/",
    "recipeTitle": "Cheeseburger Pockets",
    "cookingTimeDetails": "Prep: 30 min. Bake: 10 min.",
    "servings": "5 servings",
    "ingredients": ["1/2 pound ground beef", "1 tablespoon chopped onion", "1/2 teaspoon salt", "1/8 teaspoon pepper", "1 tube (12 ounces) refrigerated buttermilk biscuits", "5 slices process American cheese"],
    "directions": ["Preheat oven to 400°. In a large skillet, cook beef, onion, salt and pepper over medium heat until meat is no longer pink; drain and cool.", "Place 2 biscuits overlapping on a floured surface; roll out into a 5-in. oval. Place about 1/4 cup of meat mixture on 1 side. Fold a cheese slice to fit over meat mixture. Fold dough over filling; press edges with a fork to seal. Repeat with remaining biscuits, meat mixture and cheese.", "Place on a greased baking sheet. Prick tops with a fork. Bake 10 minutes or until golden brown."],
    "nutritionDetails": "1 serving: 299 calories, 10g fat (5g saturated fat), 36mg cholesterol, 1101mg sodium, 34g carbohydrate (1g sugars, 0 fiber), 17g protein."
  },
  {
    "id": 19, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Taco-Filled-Pasta-Shells_EXPS_GHBZ18_13814_E08_15_4b-3.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/taco-filled-pasta-shells/",
    "recipeTitle": "Taco-Filled Pasta Shells",
    "cookingTimeDetails": "Prep: 20 min. + chilling Bake: 45 min.",
    "servings": "2 casseroles (6 servings each)",
    "ingredients": ["2 pounds ground beef", "2 envelopes taco seasoning", "1-1/2 cups water", "1 package (8 ounces) cream cheese, cubed", "24 uncooked jumbo pasta shells", "1/4 cup butter, melted", "ADDITIONAL INGREDIENTS (for each casserole):", "1 cup salsa", "1 cup taco sauce", "1 cup shredded cheddar cheese", "1 cup shredded Monterey Jack cheese", "1-1/2 cups crushed tortilla chips", "1 cup sour cream", "3 green onions, chopped"],
    "directions": ["In a Dutch oven, cook beef over medium heat until no longer pink; drain. Stir in taco seasoning and water. Bring to a boil. Reduce heat; simmer, uncovered, for 5 minutes. Stir in cream cheese until melted. Transfer to a bowl; cool. Chill for 1 hour.", "Cook pasta according to package directions; drain. Gently toss with butter. Fill each shell with about 3 tablespoons of meat mixture. Place 12 filled shells in a freezer container. Cover and freeze for up to 3 months.", "To prepare remaining 12 stuffed shells, spoon 1 cup salsa into a greased 9-in. square baking dish. Top with shells and 1 cup taco sauce. Cover and bake at 350° for 30 minutes. Uncover; sprinkle with 1 cup of each cheese and 1-1/2 cups chips. Bake 15 minutes longer or until heated through. Serve with sour cream and onions.", "Freeze option: To use frozen shells, thaw in the refrigerator for 24 hours (shells will be partially frozen). Spoon 1 cup salsa into a greased 9-in. square baking dish; top with shells and 1 cup taco sauce. Cover and bake at 350° for 40 minutes. Uncover. Sprinkle with 1 cup of each cheese and 1-1/2 cups chips. Bake 15 minutes longer or until heated through. Serve with sour cream and onions."],
    "nutritionDetails": "2 shells: 492 calories, 31g fat (16g saturated fat), 98mg cholesterol, 982mg sodium, 29g carbohydrate (4g sugars, 1g fiber), 23g protein."
  },
  {
    "id": 20,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Over-the-Top-Mac-n-Cheese_exps36600_CF2345613A06_21_2bC_RMS-2.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/over-the-top-mac-n-cheese/",
    "recipeTitle": "Over-the-Top Mac ‘n’ Cheese",
    "cookingTimeDetails": "Prep: 15 min. Bake: 40 min.",
    "servings": "7 servings",
    "ingredients": ["1 package (16 ounces) elbow macaroni", "1/2 cup shredded Muenster cheese", "1/2 cup shredded mild cheddar cheese", "1/2 cup shredded sharp cheddar cheese", "1/2 cup shredded Monterey Jack cheese", "1/2 cup plus 1 tablespoon butter, divided", "2 cups half-and-half cream", "2 large eggs, lightly beaten", "1 cup cubed process cheese (Velveeta)", "1/4 teaspoon seasoned salt", "1/8 teaspoon pepper"],
    "directions": ["Preheat oven to 350°. Cook macaroni according to package directions. Meanwhile, combine Muenster, cheddar and Monterey Jack cheeses; set aside.", "In a large saucepan, melt 1/2 cup butter over medium heat. Stir in cream, eggs, process cheese, seasonings and 1-1/2 cups of cheese mixture. Drain pasta; add to cheese mixture and stir to coat.", "Transfer to a greased 2-1/2-qt. baking dish. Sprinkle with remaining cheese mixture and dot with remaining butter. Bake, uncovered, until a thermometer reads 160°, 40-45 minutes."],
    "nutritionDetails": "1-1/4 cups: 585 calories, 33g fat (20g saturated fat), 161mg cholesterol, 550mg sodium, 51g carbohydrate (6g sugars, 2g fiber), 20g protein."
  },
  {
    "id": 21,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Loaded-Spaghetti-Bake_EXPS_13X9BZ19_42614_E10_03_8b-5.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/loaded-spaghetti-bake/",
    "recipeTitle": "Loaded Spaghetti Bake",
    "cookingTimeDetails": "Prep: 25 min. Bake: 30 min.",
    "servings": "8 servings",
    "ingredients": ["12 ounces uncooked spaghetti", "1 pound lean ground beef (90% lean)", "1 cup chopped onion", "1 cup chopped green pepper", "1 jar (26 ounces) spaghetti sauce", "1 can (4 ounces) mushroom stems and pieces, drained", "1 can (2-1/4 ounces) sliced ripe olives, drained", "2 cups shredded cheddar cheese, divided", "1 can (10-3/4 ounces) condensed cream of chicken soup, undiluted", "1 carton (10 ounces) refrigerated Alfredo sauce", "1/4 cup grated Parmesan cheese", "1/2 cup cornflake crumbs"],
    "directions": ["Preheat oven to 350°. Cook spaghetti according to package directions. Meanwhile, in a large skillet, cook the beef, onion and pepper over medium heat until meat is no longer pink; crumble meat; drain. Add the spaghetti sauce, mushrooms and olives. Drain spaghetti; add to skillet.", "Transfer to a greased 13x9-in. baking dish. Sprinkle with 1 cup cheddar cheese. In a small bowl, combine the soup, Alfredo sauce and Parmesan cheese; spread over cheddar cheese. In another bowl, combine cornflake crumbs and remaining 1 cup cheddar cheese; sprinkle over the top.", "Bake, uncovered, until casserole is bubbly and cheese is melted, 30 minutes. Let stand 5 minutes before serving. Freeze option:Cover and freeze casserole for up to 3 months.To use, remove from the freezer 30 minutes before baking (do not thaw). Cover and bake for 1 hour. Uncover casserole and bake until heated through and a thermometer reads 165°, 15-20 minutes longer."],
    "nutritionDetails": "1-1/2 cups: 612 calories, 30g fat (14g saturated fat), 80mg cholesterol, 1486mg sodium, 55g carbohydrate (10g sugars, 4g fiber), 29g protein."
  },
  {
    "id": 22,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Skillet-Beef-and-Macaroni_EXPS_SDAS18_4467_D03_29__9b.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/skillet-beef-and-macaroni/",
    "recipeTitle": "Skillet Beef and Macaroni",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "6 servings",
    "ingredients": ["1-1/2 pound ground beef", "1/2 cup chopped onion", "2 cans (8 ounces each) tomato sauce", "1 cup water", "1 package (7 ounces) macaroni", "1/2 cup chopped green pepper", "2 tablespoons Worcestershire sauce", "1 teaspoon salt", "1/4 teaspoon pepper"],
    "directions": ["In a large skillet over medium-high heat, cook beef and onion until the meat is no longer pink; crumble meat; drain. Stir in rest of ingredients; bring to a boil. Reduce heat; simmer, covered, until macaroni is tender, 20-25 minutes; stir occasionally. Add water if needed."],
    "nutritionDetails": "1 cup: 317 calories, 11g fat (5g saturated fat), 56mg cholesterol, 700mg sodium, 29g carbohydrate (3g sugars, 2g fiber), 25g protein."
  },
  {
    "id": 23,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Favorite-Baked-Spaghetti_EXPS26331_CS2919398C04_30_8b_RMS-33.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/favorite-baked-spaghetti/",
    "recipeTitle": "Favorite Baked Spaghetti",
    "cookingTimeDetails": "Prep: 25 min. Bake: 1 hour + standing",
    "servings": "10 servings",
    "ingredients": ["1 package (16 ounces) spaghetti", "1 pound ground beef", "1 medium onion, chopped", "1 jar (24 ounces) pasta sauce", "1/2 teaspoon seasoned salt", "2 large eggs", "1/3 cup grated Parmesan cheese", "5 tablespoons butter, melted", "2 cups 4% cottage cheese", "4 cups shredded part-skim mozzarella cheese", "Chopped fresh basil, optional"],
    "directions": ["Preheat oven to 350°. Cook spaghetti according to package directions for al dente. Meanwhile, in a large skillet, cook beef and onion over medium heat until beef is no longer pink and onion is tender, 6-8 minutes, breaking beef into crumbles; drain. Stir in pasta sauce and seasoned salt; set aside.", "In a large bowl, whisk the eggs, Parmesan cheese and butter. Drain spaghetti; add to egg mixture and toss to coat.", "Place half the spaghetti mixture in a greased 13x9-in. or 3-qt. baking dish. Top with half the cottage cheese, meat sauce and mozzarella cheese. Repeat layers. Place baking dish on a rimmed baking sheet.", "Cover and bake for 40 minutes. Uncover; bake until heated through, 20-25 minutes longer. Let stand 15 minutes before serving. If desired, sprinkle with basil."],
    "nutritionDetails": "1-1/4 cups: 526 calories, 24g fat (13g saturated fat), 127mg cholesterol, 881mg sodium, 45g carbohydrate (9g sugars, 3g fiber), 31g protein."
  },
  {
    "id": 24,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Skillet-Mac-Cheese_EXPS_TOH5ICFRTL21_27614_E07_15_3b.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/skillet-mac-cheese/",
    "recipeTitle": "Skillet Mac & Cheese",
    "cookingTimeDetails": "Prep/Total Time: 25 min.",
    "servings": "4 servings",
    "ingredients": ["2 cups uncooked pasta (about 8 ounces), such as elbow macaroni, cavatappi or shells", "2 tablespoons butter", "2 tablespoons all-purpose flour", "1-1/2 cups half-and-half cream", "3/4 pound process cheese (Velveeta), cubed", "Optional toppings: Fresh arugula, halved cherry tomatoes and coarsely ground pepper"],
    "directions": ["Cook pasta according to package directions; drain.", "Meanwhile, in a large cast-iron or other heavy skillet, melt butter over medium heat. Stir in flour until smooth; gradually whisk in cream. Bring to a boil, stirring constantly. Cook and stir until thickened, about 2 minutes. Reduce heat; stir in cheese until melted.", "Add macaroni; cook and stir until heated through. Top as desired."],
    "nutritionDetails": "1-1/2 cups: 600 calories, 37g fat (23g saturated fat), 144mg cholesterol, 1185mg sodium, 40g carbohydrate (9g sugars, 1g fiber), 23g protein."
  },
  {
    "id": 25,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Oven-Fried-Fish-Nuggets_exps35083_THD143241C01_22_5bC_RMS-2.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/oven-fried-fish-nuggets/",
    "recipeTitle": "Oven-Fried Fish Nuggets",
    "cookingTimeDetails": "Prep/Total Time: 25 min.",
    "servings": "4 servings",
    "ingredients": ["1/3 cup seasoned bread crumbs", "1/3 cup crushed cornflakes", "3 tablespoons grated Parmesan cheese", "1/2 teaspoon salt", "1/4 teaspoon pepper", "1-1/2 pounds cod fillets, cut into 1-inch cubes", "Butter-flavored cooking spray"],
    "directions": ["In a shallow bowl, combine the bread crumbs, cornflakes, Parmesan cheese, salt and pepper. Coat fish with butter-flavored spray, then roll in crumb mixture.", "Place on a baking sheet coated with cooking spray. Bake at 375° for 15-20 minutes or until fish flakes easily with a fork. Freeze option: Cover and freeze unbaked fish nuggets on a waxed paper-lined baking sheet until firm. Transfer to a resealable freezer container; return to freezer. To use, preheat oven to 375°. Bake nuggets on a rack on a greased baking sheet 15-20 minutes or until fish flakes easily with a fork."],
    "nutritionDetails": "9 piece: 171 calories, 2g fat (1g saturated fat), 66mg cholesterol, 415mg sodium, 7g carbohydrate (1g sugars, 0 fiber), 29g protein. Diabetic Exchanges: 5 lean meat, 1/2 starch."
  },
  {
    "id": 26,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Stovetop-Beef-and-Shells_EXPS_SDON17_27668_D07_06_3b-1.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/stovetop-beef-and-shells/",
    "recipeTitle": "Stovetop Beef and Shells",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "4 servings",
    "ingredients": ["1-1/2 cups uncooked medium pasta shells (about 4 ounces)", "1 pound lean ground beef (90% lean)", "1 medium onion, chopped", "1 garlic clove, minced", "1 can (15 ounces) crushed tomatoes", "1 can (8 ounces) tomato sauce", "1 teaspoon sugar", "1/2 teaspoon salt", "1/2 teaspoon pepper"],
    "directions": ["Cook pasta according to package directions; drain.", "Meanwhile, in a large skillet, cook and crumble beef with onion and garlic over medium-high heat until no longer pink, 5-7 minutes. Stir in remaining ingredients; bring to a boil. Reduce heat; simmer, uncovered, until flavors are blended, 10-15 minutes.", "Stir in pasta; heat through."],
    "nutritionDetails": "1-1/4 cups: 344 calories, 11g fat (4g saturated fat), 71mg cholesterol, 815mg sodium, 35g carbohydrate (9g sugars, 4g fiber), 29g protein. Diabetic Exchanges: 3 lean meat, 2 starch, 1 vegetable."
  },
  {
    "id": 27,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps21669_FF163882B01_13_4b-1.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/hot-dog-pie/",
    "recipeTitle": "Hot Dog Pie",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "6 servings",
    "ingredients": ["1/2 pound ground beef", "4 hot dogs, cut in half lengthwise and sliced", "1 can (16 ounces) baked beans", "1/2 cup ketchup", "2 tablespoons brown sugar", "2 tablespoons prepared mustard", "2 ounces process cheese (Velveeta), cubed", "1 frozen deep-dish pie crust (9 inches)", "4 slices American cheese"],
    "directions": ["Preheat oven to 400°. In a large saucepan, cook beef over medium heat until no longer pink; drain. Add hot dogs, beans, ketchup, brown sugar, mustard and cheese cubes. Cook and stir until cheese is melted.", "Meanwhile, prick crust with a fork. Bake for 10 minutes. Fill with hot beef mixture. Cut each cheese slice into four strips; make a lattice topping over pie. Bake until cheese is melted, 5-10 minutes longer."],
    "nutritionDetails": "1 piece: 487 calories, 27g fat (11g saturated fat), 62mg cholesterol, 1321mg sodium, 43g carbohydrate (13g sugars, 5g fiber), 21g protein."
  },
  {
    "id": 28,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps116189___SD153320C12_05_6b-2.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/frito-pie/",
    "recipeTitle": "Frito Pie",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "6 servings",
    "ingredients": ["1 pound ground beef", "1 medium onion, chopped", "2 cans (15 ounces each) Ranch Style beans (pinto beans in seasoned tomato sauce)", "1 package (9-1/4 ounces) Frito corn chips", "2 cans (10 ounces each) enchilada sauce", "2 cups shredded cheddar cheese", "Thinly sliced green onions, optional"],
    "directions": ["Preheat oven to 350°. In a large skillet, cook beef and onion over medium heat 6-8 minutes or until beef is no longer pink and onion is tender, breaking up beef into crumbles; drain. Stir in beans; heat through.", "Reserve 1 cup corn chips for topping. Place remaining corn chips in a greased 13x9-in. baking dish. Layer with meat mixture, enchilada sauce and cheese; top with reserved chips.", "Bake, uncovered, 15-20 minutes or until cheese is melted. If desired, sprinkle with green onions."],
    "nutritionDetails": "1 serving: 731 calories, 41g fat (14g saturated fat), 84mg cholesterol, 1733mg sodium, 54g carbohydrate (6g sugars, 8g fiber), 34g protein."
  },
  {
    "id": 29,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Bacon-Cheeseburger-Tater-Tot-Bake_EXPS_THFM17_195129_B09_28_2b-11.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/bacon-cheeseburger-tater-tot-bake/",
    "recipeTitle": "Bacon Cheeseburger Tater Tot Bake",
    "cookingTimeDetails": "Prep: 15 min. Bake: 35 min.",
    "servings": "12 servings",
    "ingredients": ["2 pounds ground beef", "1 large onion, chopped and divided", "1 can (15 ounces) tomato sauce", "1 tablespoon ground mustard", "1 tablespoon Worcestershire sauce", "1 package (8 ounces) Velveeta", "2 cups shredded cheddar cheese", "12 bacon strips, cooked and crumbled", "1 package (32 ounces) frozen Tater Tots", "1 cup grape tomatoes, chopped", "1/3 cup sliced dill pickles"],
    "directions": ["Preheat oven to 400°. In a large skillet over medium heat, cook beef and 1 cup onion, crumbling meat, until beef is no longer pink and onion is tender, 6-8 minutes; crumble meat; drain. Stir in tomato sauce, Velveeta, mustard and Worcestershire sauce until cheese is melted, 4-6 minutes.", "Transfer to a greased 13x9-in. or 3-1/2-qt. baking dish. Sprinkle with cheddar cheese and bacon. Top with Tater Tots. Bake, uncovered, 35-40 minutes or until bubbly. Top with tomatoes, pickles and remaining onion."],
    "nutritionDetails": "1 cup: 479 calories, 31g fat (12g saturated fat), 92mg cholesterol, 1144mg sodium, 24g carbohydrate (4g sugars, 3g fiber), 27g protein."
  },
  {
    "id": 30,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps25759__SD143206C04_08_4b-6.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/garlic-toast-pizzas/",
    "recipeTitle": "Garlic Toast Pizzas",
    "cookingTimeDetails": "Prep/Total Time: 15 min.",
    "servings": "8 slices",
    "ingredients": ["1 package (11-1/4 ounces) frozen garlic Texas toast", "1/2 cup pizza sauce", "1 package (3-1/2 ounces) sliced regular or turkey pepperoni", "2 cups shredded part-skim mozzarella cheese"],
    "directions": ["Preheat oven to 425°. Place Texas toast in a 15x10x1-in. baking pan. Bake 5 minutes.", "Spread toast with pizza sauce; top with pepperoni and cheese. Bake until cheese is melted, 4-5 minutes longer."],
    "nutritionDetails": "1 slice: 281 calories, 20g fat (8g saturated fat), 58mg cholesterol, 610mg sodium, 14g carbohydrate (3g sugars, 1g fiber), 12g protein."
  },
  {
    "id": 31,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Mini-Shepherd-s-Pies_EXPS_SDAS17_38061_C04_07_6b-8.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/mini-shepherd-s-pies/",
    "recipeTitle": "Mini Shepherd’s Pies",
    "cookingTimeDetails": "Prep: 30 min. Bake: 20 min.",
    "servings": "5 servings",
    "ingredients": ["1 pound ground beef", "1/4 cup chopped onion", "1 garlic clove, minced", "1/3 cup chili sauce or ketchup", "1 tablespoon cider vinegar", "1-1/4 cups water", "3 ounces cream cheese, cubed", "3 tablespoons butter", "1-1/4 cups mashed potato flakes", "2 tubes (6 ounces each) small refrigerated buttermilk biscuits", "1/2 cup crushed potato chips", "Paprika, optional"],
    "directions": ["Preheat oven to 375°. In a large skillet, cook and crumble beef with onion and garlic over medium heat until no longer pink, 5-7 minutes; drain. Stir in chili sauce and vinegar.", "In a small saucepan, combine water, cream cheese and butter; bring to a boil. Remove from heat; stir in potato flakes.", "Separate biscuits; press each onto bottom and up sides of a greased muffin cup. Fill with beef mixture; top with mashed potatoes. Sprinkle with potato chips.", "Bake until topping is golden brown, 20-25 minutes. If desired, sprinkle with paprika.", "Freeze option: Freeze cooled pies in a single layer in freezer containers. To use, partially thaw in refrigerator overnight. Reheat on a baking sheet in a preheated 375° oven until heated through, 15-18 minutes."],
    "nutritionDetails": "2 mini shepherd's pies: 612 calories, 36g fat (15g saturated fat), 92mg cholesterol, 1094mg sodium, 49g carbohydrate (11g sugars, 2g fiber), 24g protein."
  },
  {
    "id": 32,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps17941_CAS143580B09_16_3b.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/ham-noodle-dinner/",
    "recipeTitle": "Ham Noodle Dinner",
    "cookingTimeDetails": "Prep: 15 min. Bake: 50 min.",
    "servings": "6 servings",
    "ingredients": ["2-1/2 cups uncooked egg noodles", "1 celery rib, chopped", "1 medium onion, chopped", "1 tablespoon canola oil", "2 cups cubed fully cooked ham", "1 can (10-3/4 ounces) condensed cream of mushroom soup, undiluted", "1 package (10 ounces) frozen peas, thawed", "1 cup shredded cheddar cheese", "3/4 cup 2% milk", "1 teaspoon ground mustard"],
    "directions": ["Cook noodles according to package directions; drain. Meanwhile, in a large skillet, saute celery and onion in oil until tender. Stir in noodles and remaining ingredients.", "Transfer to a greased 2-qt. baking dish. Cover and bake at 350° for 50-60 minutes or until heated through."],
    "nutritionDetails": "1-1/2 cups: 332 calories, 16g fat (7g saturated fat), 66mg cholesterol, 1144mg sodium, 28g carbohydrate (6g sugars, 4g fiber), 20g protein."
  },
  {
    "id": 33, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/One-Skillet-Pasta_EXPS_CIMZ19_45549_C01_09_8b-13.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/one-skillet-pasta/",
    "recipeTitle": "One-Skillet Pasta",
    "cookingTimeDetails": "Prep: 20 min. Cook: 1-1/4 hours",
    "servings": "5 servings",
    "ingredients": ["1-1/2 pounds ground turkey", "1 medium onion, finely chopped", "1 medium sweet red pepper, finely chopped", "1 can (28 ounces) diced tomatoes, undrained", "1 can (14-1/2 ounces) fire-roasted diced tomatoes, undrained", "1 can (14-1/2 ounces) reduced-sodium beef broth", "1 can (4 ounces) sliced mushrooms, drained", "1 tablespoon packed brown sugar", "1 tablespoon chili powder", "8 ounces uncooked angel hair pasta", "1 cup shredded cheddar cheese"],
    "directions": ["In a large cast-iron or other heavy skillet, cook the turkey, onion and pepper over medium heat until meat is no longer pink; drain.", "Add the tomatoes, broth, mushrooms, brown sugar and chili powder. Bring to a boil. Reduce heat; simmer, uncovered, for 30 minutes.", "Add pasta; return to a boil. Reduce heat; cover and simmer until pasta is tender, 30-35 minutes. Sprinkle with cheese. Cover and cook until cheese is melted, 2-3 minutes longer."],
    "nutritionDetails": "1-2/3 cups: 553 calories, 19g fat (7g saturated fat), 114mg cholesterol, 994mg sodium, 55g carbohydrate (14g sugars, 7g fiber), 41g protein."
  },
  {
    "id": 34,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Two-Tater-Shepherd-s-Pie_exps21052_THCAS2302838B05_19_4bC_RMS-1.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/two-tater-shepherd-s-pie/",
    "recipeTitle": "Two-Tater Shepherd’s Pie",
    "cookingTimeDetails": "Prep: 20 min. Bake: 40 min.",
    "servings": "8 servings",
    "ingredients": ["1-1/2 pounds ground beef", "1 can (10-3/4 ounces) condensed cream of mushroom soup, undiluted", "1/2 teaspoon garlic salt", "1/4 teaspoon pepper", "6 cups frozen Tater Tots", "2 cups frozen French-style green beans, thawed", "3 cups hot mashed potatoes", "1 cup shredded Colby cheese"],
    "directions": ["In a large skillet, cook beef over medium heat until no longer pink; drain. Stir in the soup, garlic salt and pepper.", "Place Tater Tots in a greased 13-in. x 9-in. baking dish. Top with beef mixture and green beans. Spread mashed potatoes over the top; sprinkle with cheese.", "Bake, uncovered, at 350° until heated through, 40-45 minutes."],
    "nutritionDetails": "1 cup: 550 calories, 32g fat (12g saturated fat), 81mg cholesterol, 1241mg sodium, 48g carbohydrate (2g sugars, 5g fiber), 25g protein."
  },
  {
    "id": 35,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps179236_TH143194A06_06_2b-7.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/muffin-tin-pizzas/",
    "recipeTitle": "Muffin-Tin Pizzas",
    "cookingTimeDetails": "Prep: 25 min. Bake: 10 min.",
    "servings": "16 mini pizzas",
    "ingredients": ["1 can (15 ounces) tomato sauce", "1 can (6 ounces) tomato paste", "1 teaspoon dried basil", "1/2 teaspoon garlic salt", "1/4 teaspoon onion powder", "1/4 teaspoon sugar", "1 tube (11 ounces) refrigerated thin pizza crust", "1-1/2 cups shredded part-skim mozzarella cheese", "1/2 cup finely chopped fresh mushrooms", "1/2 cup finely chopped fresh broccoli", "16 slices pepperoni, halved"],
    "directions": ["Preheat oven to 425°. In a small bowl, mix the first 6 ingredients.", "Unroll pizza crust; cut into 16 squares. Press squares onto bottoms and up sides of 16 ungreased muffin cups, allowing corners to hang over the edges.", "Spoon 1 tablespoon sauce mixture into each cup. Top with cheese, mushrooms, broccoli and pepperoni. Bake until crusts are golden brown, 10-12 minutes. Serve with remaining sauce mixture, warmed if desired.", "Freeze option: Freeze cooled baked pizzas in an airtight container. To use, reheat pizzas on a baking sheet in a preheated 425° oven until heated through."],
    "nutritionDetails": "2 pizzas with 2 tablespoons sauce: 233 calories, 9g fat (4g saturated fat), 16mg cholesterol, 755mg sodium, 26g carbohydrate (5g sugars, 2g fiber), 12g protein."
  },
  {
    "id": 36,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Santa-Fe-Skillet_EXPS_OPBZ18_23272_C06_29_4b-11.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/santa-fe-skillet/",
    "recipeTitle": "Santa Fe Skillet",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "6 servings",
    "ingredients": ["1 pound lean ground beef (90% lean)", "1 small onion, chopped", "1 package (6 ounces) four-cheese corkscrew pasta mix", "2 cups salsa", "1 cup hot water", "1 tablespoon chili powder", "1/2 teaspoon salt", "Dash cayenne pepper", "1 can (14-1/2 ounces) diced tomatoes, undrained", "1 can (2-1/4 ounces) sliced ripe olives, drained", "1 cup shredded cheddar cheese", "Sour cream, optional"],
    "directions": ["In a large skillet, cook beef and onion over medium heat until meat is no longer pink; crumble meat; drain. Stir in the pasta, contents of seasoning packet, salsa, water, chili powder, salt and cayenne.", "Bring to a boil. Reduce heat; cover and simmer until pasta is tender, about 15 minutes, adding more water if necessary. Stir in tomatoes; sprinkle with olives and cheese. Cover and simmer until heated through, 3-4 minutes. Serve with sour cream if desired."],
    "nutritionDetails": "1-1/4 cups: 287 calories, 10g fat (3g saturated fat), 49mg cholesterol, 1061mg sodium, 29g carbohydrate (7g sugars, 3g fiber), 19g protein."
  },
  {
    "id": 37, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Ham-and-Scalloped-Potatoes_EXPS_SDDJ19_13255_C07_13_1b-2.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/ham-and-scalloped-potatoes/",
    "recipeTitle": "Ham and Scalloped Potatoes",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "4 servings",
    "ingredients": ["4 medium potatoes, peeled and thinly sliced", "2 tablespoons butter", "1/3 cup water", "1/2 cup 2% milk", "2 to 3 tablespoons onion soup mix", "3 tablespoons minced fresh parsley", "1 cup cubed Velveeta", "1 cup cubed fully cooked ham"],
    "directions": ["In a large skillet, cook potatoes in butter until potatoes are lightly browned. Add water; bring to a boil. Reduce heat; cover and simmer for 14-15 minutes or until potatoes are tender.", "Meanwhile in a small bowl, combine the milk, soup mix and parsley; stir in cheese. Pour over potatoes. Add ham; cook and stir gently over medium heat until cheese is melted and sauce is bubbly."],
    "nutritionDetails": "1 serving: 353 calories, 17g fat (10g saturated fat), 56mg cholesterol, 1170mg sodium, 36g carbohydrate (6g sugars, 2g fiber), 16g protein."
  },
  {
    "id": 38, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps181639_TH153340C09_26_8b-4.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/double-crust-pizza-casserole/",
    "recipeTitle": "Double-Crust Pizza Casserole",
    "cookingTimeDetails": "Prep: 20 min. Bake: 20 min.",
    "servings": "12 servings",
    "ingredients": ["2 pounds lean ground beef (90% lean)", "2 cans (15 ounces each) pizza sauce, divided", "2 teaspoons dried oregano", "3 cups biscuit/baking mix", "1-1/4 cups 2% milk", "1 large egg, lightly beaten", "2 cups shredded part-skim mozzarella cheese", "1 cup sliced fresh mushrooms", "1 medium green pepper, chopped", "1 medium onion, chopped", "1/4 cup grated Parmesan cheese", "1 plum tomato, chopped"],
    "directions": ["Preheat oven to 400°. In a large skillet, cook beef over medium heat until no longer pink, 8-10 minutes, breaking into crumbles; drain. Stir in 1 can pizza sauce and oregano. Bring to a boil. Reduce heat; simmer, uncovered, until slightly thickened, 5-6 minutes, stirring occasionally. Remove from heat.", "In a large bowl, combine biscuit mix, milk and egg; stir just until moistened. Spread half the batter onto bottom of a greased 13x9-in. baking pan. Spread with remaining pizza sauce. Top with mozzarella cheese, mushrooms, pepper, onion and beef mixture. Spoon remaining batter over top; sprinkle with Parmesan cheese.", "Bake, uncovered, until golden brown, 20-25 minutes. Sprinkle with tomato. Let stand 5 minutes before serving."],
    "nutritionDetails": "1 piece: 369 calories, 16 g fat (7 g saturated fat), 78 mg cholesterol, 710 mg sodium, 30 g carbohydrate (4 g sugars, 3 g fiber), 26 g protein."
  },
  {
    "id": 39,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps113889_SD163615C04_07_7b-5.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/sloppy-joe-biscuit-cups/",
    "recipeTitle": "Sloppy Joe Biscuit Cups",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "10 biscuit cups",
    "ingredients": ["1 pound lean ground beef (90% lean)", "1/4 cup each finely chopped celery, onion and green pepper", "1/2 cup barbecue sauce", "1 tube (12 ounces) refrigerated flaky biscuits (10 count)", "1/2 cup shredded cheddar cheese"],
    "directions": ["Heat oven to 400°. In a large skillet, cook beef and vegetables over medium heat until beef is no longer pink, 5-7 minutes, breaking up beef into crumbles; drain. Stir in barbecue sauce; bring to a boil. Reduce heat; simmer, uncovered, 2 minutes, stirring occasionally.", "Separate dough into 10 biscuits; flatten to 5-in. circles. Press onto bottoms and up sides of greased muffin cups. Fill with beef mixture.", "Bake until biscuits are golden brown, 9-11 minutes. Sprinkle with cheese; bake until cheese is melted, 1-2 minutes longer."],
    "nutritionDetails": "2 biscuit cups : 463 calories, 22g fat (8g saturated fat), 68mg cholesterol, 1050mg sodium, 41g carbohydrate (16g sugars, 1g fiber), 25g protein."
  },
  {
    "id": 40, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps16436_FF163882C01_13_3b-2.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/hot-dog-roll-ups/",
    "recipeTitle": "Hot Dog Roll-Ups",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "8 servings",
    "ingredients": ["8 hot dogs", "1 block (4 ounces) cheddar cheese, cut into 8 strips", "2 bacon strips, cooked and crumbled", "1 tube (8 ounces) refrigerated crescent rolls"],
    "directions": ["Cut a lengthwise slit in each hot dog; fill with a strip of cheese and about 1/2 teaspoon bacon. Separate crescent dough into 8 triangles. Place a hot dog on the wide end of each triangle; roll toward the point. Place cheese side up on an ungreased baking sheet. Bake at 375° until golden brown, 12 minutes or until golden brown."],
    "nutritionDetails": "1 each: 325 calories, 25g fat (10g saturated fat), 41mg cholesterol, 797mg sodium, 12g carbohydrate (3g sugars, 0 fiber), 11g protein."
  },
  {
    "id": 41,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps47591_TH153340D09_24_1b-1.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/hearty-beef-ravioli/",
    "recipeTitle": "Hearty Beef Ravioli",
    "cookingTimeDetails": "Prep/Total Time: 25 min.",
    "servings": "6 servings",
    "ingredients": ["1 package (25 ounces) frozen beef ravioli", "1/2 pound extra-lean ground beef (95% lean)", "1 medium green pepper, chopped", "1 can (14-1/2 ounces) no-salt-added diced tomatoes, undrained", "1 can (8 ounces) no-salt-added tomato sauce", "2 tablespoons reduced-sodium taco seasoning", "3/4 cup shredded reduced-fat cheddar cheese", "1 can (2-1/4 ounces) sliced ripe olives, drained"],
    "directions": ["Cook ravioli according to package directions; drain.", "Meanwhile, in a large nonstick skillet, cook beef and pepper over medium heat 4-6 minutes or until beef is no longer pink, breaking up beef into crumbles. Stir in tomatoes, tomato sauce and taco seasoning. Bring to a boil. Reduce heat; simmer, uncovered, 5-7 minutes or until slightly thickened.", "Serve with ravioli. Top with cheese and olives."],
    "nutritionDetails": "1 serving: 375 calories, 10g fat (5g saturated fat), 44mg cholesterol, 695mg sodium, 49g carbohydrate (7g sugars, 4g fiber), 21g protein."
  },
  {
    "id": 42, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps12399_THCA173831D03_29_3b.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/ham-and-cheese-puffs/",
    "recipeTitle": "Ham and Cheese Puffs",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "2 dozen",
    "ingredients": ["1 package (2-1/2 ounces) thinly sliced deli ham, chopped", "1 small onion, chopped", "1/2 cup shredded Swiss cheese", "1 large egg", "1-1/2 teaspoons Dijon mustard", "1/8 teaspoon pepper", "1 tube (8 ounces) refrigerated crescent rolls"],
    "directions": ["Preheat oven to 375°. Combine the first six ingredients. Divide crescent dough into 24 portions. Press into greased mini muffin cups.", "Spoon 1 tablespoon ham mixture into each cup. Bake until golden brown, 13-15 minutes."],
    "nutritionDetails": "1 appetizer: 110 calories, 6g fat (2g saturated fat), 25mg cholesterol, 263mg sodium, 8g carbohydrate (2g sugars, 0 fiber), 4g protein."
  },
  {
    "id": 43,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Muffin-Cup-Cheddar-Beef-Pies_exps166713_SD143203B10_16_10bC_RMS.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/muffin-cup-cheddar-beef-pies/",
    "recipeTitle": "Muffin-Cup Cheddar Beef Pies",
    "cookingTimeDetails": "Prep: 25 min. + standing Bake: 20 min.",
    "servings": "20 meat pies",
    "ingredients": ["2 loaves (1 pound each) frozen bread dough", "2 pounds ground beef", "1 can (8 ounces) mushroom stems and pieces, drained", "1-1/4 cups shredded cheddar cheese", "1-1/2 teaspoons Italian seasoning", "1 teaspoon garlic powder", "1/2 teaspoon salt", "1/4 teaspoon pepper", "Spaghetti sauce, warmed"],
    "directions": ["Let dough stand at room temperature until softened, about 30 minutes. Preheat oven to 350°. Meanwhile, in a Dutch oven, cook beef over medium heat until no longer pink, breaking into crumbles, 12-15 minutes; crumble meat; drain. Stir in mushrooms, cheese and seasonings.", "Divide each loaf of dough into 10 portions; roll each portion into a 4-in. circle. Top each circle with 1/4 cup filling; bring edges of dough up over filling and pinch to seal.", "Place meat pies in greased muffin cups, seam side down. Bake until golden brown, 20-25 minutes. Serve with spaghetti sauce.", "Freeze option: Freeze cooled pies in a freezer container. To use, reheat beef pies on greased baking sheets in a preheated 350° oven until heated through."],
    "nutritionDetails": "2 meat pies: 482 calories, 19g fat (7g saturated fat), 71mg cholesterol, 850mg sodium, 45g carbohydrate (4g sugars, 4g fiber), 29g protein."
  },
  {
    "id": 44, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Chili-ghetti_EXPS_SDFM19_16418_C10_18_6b-11.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/chili-ghetti/",
    "recipeTitle": "Chili-ghetti",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "6 servings",
    "ingredients": ["1 package (7 ounces) spaghetti", "1 pound ground beef", "1 small onion, chopped", "1 can (16 ounces) kidney beans, rinsed and drained", "1 can (14-1/2 ounces) no-salt-added diced tomatoes, undrained", "1 can (4 ounces) mushroom stems and pieces, drained", "1/3 cup water", "1 envelope chili seasoning", "2 tablespoons grated Parmesan cheese", "1/4 cup shredded part-skim mozzarella cheese"],
    "directions": ["Cook spaghetti according to package directions. Meanwhile, in a large skillet, cook beef and onion over medium heat until meat is no longer pink; crumble beef; drain.", "Drain spaghetti; add to beef mixture. Stir in the beans, tomatoes, mushrooms, water, chili seasoning and Parmesan cheese. Cover and simmer for 10 minutes. Sprinkle with mozzarella cheese."],
    "nutritionDetails": "1-1/4 cups: 374 calories, 11g fat (4g saturated fat), 51mg cholesterol, 706mg sodium, 43g carbohydrate (5g sugars, 6g fiber), 25g protein."
  },
  {
    "id": 45, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Waffle-Iron-Pizzas_EXPS_TOHFM21_187180_E09_22_13b.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/waffle-iron-pizzas/",
    "recipeTitle": "Waffle-Iron Pizzas",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "4 servings",
    "ingredients": ["1 package (16.3 ounces) large refrigerated buttermilk biscuits", "1 cup shredded part-skim mozzarella cheese", "24 slices turkey pepperoni (about 1-1/2 ounces)", "2 ready-to-serve fully cooked bacon strips, chopped", "Pizza sauce, warmed"],
    "directions": ["Roll or press biscuits to fit waffle iron. On 1 biscuit, place 1/4 cup cheese, 6 slices pepperoni and 1 scant tablespoon chopped bacon to within 1/2 in. of edges. Top with a second biscuit, folding bottom edge over top edge and pressing to seal completely.", "Bake in a preheated waffle iron according to manufacturer's directions until golden brown, 4-5 minutes. Repeat with remaining ingredients. Serve with pizza sauce."],
    "nutritionDetails": "1 pizza (calculated without sauce): 461 calories, 21g fat (8g saturated fat), 28mg cholesterol, 1650mg sodium, 50g carbohydrate (5g sugars, 2g fiber), 19g protein."
  },
  {
    "id": 46,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps182782_SD153319D10_08_3b-1.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/mama-mia-meatball-taquitos/",
    "recipeTitle": "Mama Mia Meatball Taquitos",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "6 servings",
    "ingredients": ["12 frozen fully cooked Italian turkey meatballs, thawed", "2 cups shredded part-skim mozzarella cheese", "1 cup whole-milk ricotta cheese", "1 teaspoon Italian seasoning", "12 flour tortillas (8 inches)", "Cooking spray", "Warm marinara sauce"],
    "directions": ["Preheat oven to 425°. Place meatballs in a food processor; pulse until finely chopped. Transfer to a large bowl; stir in cheeses and Italian seasoning.", "Spread about 1/4 cup meatball mixture down center of each tortilla. Roll up tightly. Place in a greased 15x10x1-in. baking pan, seam side down; spritz with cooking spray.", "Bake until golden brown, 16-20 minutes. Serve with marinara sauce."],
    "nutritionDetails": "2 taquitos: 617 calories, 28g fat (11g saturated fat), 94mg cholesterol, 1069mg sodium, 60g carbohydrate (3g sugars, 3g fiber), 33g protein."
  },
  {
    "id": 47, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/05/Fair-Favorite-Corn-Dogs_EXPS_SDJJ18_132226_C02_15_1b-1.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/fair-favorite-corn-dogs/",
    "recipeTitle": "Fair-Favorite Corn Dogs",
    "cookingTimeDetails": "Prep: 15 min. + standing Cook: 5 min./batch",
    "servings": "10 corn dogs",
    "ingredients": ["1 package (8-1/2 ounces) cornbread/muffin mix", "2/3 cup all-purpose flour", "1 teaspoon ground mustard", "1/2 teaspoon onion powder", "1/2 teaspoon chili powder", "1/2 teaspoon paprika", "1/8 teaspoon ground cumin", "1 cup 2% milk", "1 large egg", "10 hot dogs", "10 wooden skewers", "Oil for deep-fat frying"],
    "directions": ["In a large bowl, combine the first 7 ingredients. In another bowl, whisk milk and egg; stir into dry ingredients just until moistened. Let stand for 15 minutes. Insert skewers into hot dogs; dip into batter.", "In an electric skillet or deep-fat fryer, heat oil to 375°. Fry corn dogs, a few at a time, until golden brown, 2-3 minutes, turning occasionally. Drain on paper towels."],
    "nutritionDetails": "1 corn dog: 352 calories, 23g fat (7g saturated fat), 53mg cholesterol, 682mg sodium, 26g carbohydrate (7g sugars, 1g fiber), 9g protein."
  },
  {
    "id": 48, 
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/Sweet-Potato-Crusted-Chicken-Nuggets_EXPS_SDFM18_206924_C10_05_4b-3.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/sweet-potato-crusted-chicken-nuggets/",
    "recipeTitle": "Sweet Potato-Crusted Chicken Nuggets",
    "cookingTimeDetails": "Prep/Total Time: 30 min.",
    "servings": "4 servings",
    "ingredients": ["Oil for deep-fat frying", "1 cup sweet potato chips", "1/4 cup all-purpose flour", "1 teaspoon salt, divided", "1/2 teaspoon coarsely ground pepper", "1/4 teaspoon baking powder", "1 tablespoon cornstarch", "1 pound chicken tenderloins, cut into 1-1/2-inch pieces"],
    "directions": ["In an electric skillet or deep fryer, heat oil to 350°. Place chips, flour, 1/2 teaspoon salt, pepper and baking powder in a food processor; pulse until ground. Transfer to a shallow dish.", "Mix cornstarch and remaining salt; toss with chicken. Toss with potato chip mixture, pressing gently to coat.", "Fry nuggets, a few at a time, until golden brown, 2-3 minutes. Drain on paper towels."],
    "nutritionDetails": "1 serving: 308 calories, 17g fat (1g saturated fat), 56mg cholesterol, 690mg sodium, 12g carbohydrate (1g sugars, 1g fiber), 28g protein."
  },
  {
    "id": 49,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps19876_FF163882B01_14_5b.jpg?fit=700,700",
    "url": "https://www.tasteofhome.com/recipes/triple-cheese-twists/",
    "recipeTitle": "Triple Cheese Twists",
    "cookingTimeDetails": "Prep/Total Time: 25 min.",
    "servings": "8 servings",
    "ingredients": ["1 package (16 ounces) spiral pasta", "1 small onion, chopped", "1 garlic clove, minced", "6 tablespoons butter, divided", "6 tablespoons all-purpose flour", "4 cups whole milk", "1 can (14-1/2 ounces) vegetable or chicken broth", "1 cup shredded cheddar cheese", "1 cup shredded Monterey Jack cheese", "1/2 cup shredded Parmesan cheese", "1/4 cup bread crumbs", "1/2 teaspoon Italian seasoning"],
    "directions": ["Cook pasta according to package directions. Meanwhile, in a large saucepan, saute onion and garlic in 4 tablespoons butter until tender. Stir in the flour until blended. Gradually add milk and broth. Bring to a boil; cook and stir for 2 minutes or until thickened. Remove from the heat; stir in cheeses until melted.", "Melt the remaining 2 tablespoons butter; stir in bread crumbs and Italian seasoning. Drain pasta; toss with cheese sauce. Sprinkle with seasoned bread crumbs."],
    "nutritionDetails": "1 cup: 527 calories, 24g fat (15g saturated fat), 71mg cholesterol, 644mg sodium, 57g carbohydrate (9g sugars, 2g fiber), 21g protein."
  },
  {
    "id": 50,
    "isFavorited": "false",
    "image": "https://www.tasteofhome.com/wp-content/uploads/2018/06/Chicken-Taco-Pockets_EXPS_SDAS18_205120_C03_28__4b-3.jpg?fit=696,696",
    "url": "https://www.tasteofhome.com/recipes/chicken-taco-pockets/",
    "recipeTitle": "Chicken Taco Pockets",
    "cookingTimeDetails": "Prep/Total Time: 25 min.",
    "servings": "8 servings",
    "ingredients": ["2 tubes (8 ounces each) refrigerated crescent rolls", "1/2 cup salsa, plus more for serving", "1/2 cup sour cream", "2 tablespoons taco seasoning", "1 cup shredded rotisserie chicken", "1 cup shredded cheddar cheese", "Optional: Shredded lettuce, guacamole and additional sour cream"],
    "directions": ["Preheat oven to 375°. Unroll 1 tube crescent dough and separate into 2 rectangles; press perforations to seal. Repeat with second tube. In a bowl, combine salsa, sour cream and taco seasoning. Spoon chicken onto the left side of each rectangle; top with salsa mixture. Sprinkle with cheese. Fold dough over filling; pinch edges to seal.", "Place on an ungreased baking sheet. Bake until golden brown, 13-15 minutes. Cut in half. Serve with salsa and toppings as desired."],
    "nutritionDetails": "1/2 pocket: 393 calories, 24g fat (7g saturated fat), 47mg cholesterol, 896mg sodium, 29g carbohydrate (7g sugars, 0 fiber), 16g protein."
  }
]
module.exports = recipeData;